In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Bob"],
    "Age": [25, 30, 35]
})

In [7]:
df

    Name  Age
0   John   25
1  Alice   30
2    Bob   35

In [8]:
df['Age'].map(lambda x: x+10)

0    35
1    40
2    45
Name: Age, dtype: int64

In [9]:
df

    Name  Age
0   John   25
1  Alice   30
2    Bob   35

In [10]:
df['Age'].apply(lambda x: x+10)

0    35
1    40
2    45
Name: Age, dtype: int64

In [16]:
df

    Name  Age
0   John   25
1  Alice   30
2    Bob   35

In [17]:
df.apply(max)

Name    John
Age       35
dtype: object