Level 7 - Replace()

In [20]:
import pandas as pd

In [21]:
# create a dataframe of below data

# Name      Dept      Salary    Age
# John      IT        70000      25
# Sam       HR        50000      31
# Lisa      IT        90000      29
# David     Sales     60000      27
# Sara      HR        55000      35



data = {
        'Name': ['John', 'Sam', 'Lisa', 'David', 'Sara'],
        'Dept': ['IT', 'HR', 'IT', 'Sales', 'HR'],
        'Salary': [70000, 50000, 90000, 60000, 55000],
        'Age': [25, 31, 29, 27, 35]
    }
df = pd.DataFrame(data)

In [22]:
df

    Name   Dept  Salary  Age
0   John     IT   70000   25
1    Sam     HR   50000   31
2   Lisa     IT   90000   29
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [23]:
# 61

# Replace

# Male

# Female

df['Gender'] = ["Male", "Male", "Female", "Male", "Female"]

df['Gender'] = df['Gender'].replace({"Male":"M","Female":"F"})

In [24]:
df

    Name   Dept  Salary  Age Gender
0   John     IT   70000   25      M
1    Sam     HR   50000   31      M
2   Lisa     IT   90000   29      F
3  David  Sales   60000   27      M
4   Sara     HR   55000   35      F

In [25]:
# 62

# Replace

# 0

# NaN

df['Dept'] = df['Dept'].map(lambda x: 0 if x=="IT" else x)

df

    Name   Dept  Salary  Age Gender
0   John      0   70000   25      M
1    Sam     HR   50000   31      M
2   Lisa      0   90000   29      F
3  David  Sales   60000   27      M
4   Sara     HR   55000   35      F

In [26]:
import numpy as np

In [30]:
df = df.replace(0,np.nan) 
df

    Name   Dept  Salary  Age Gender
0   John    NaN   70000   25      M
1    Sam     HR   50000   31      M
2   Lisa    NaN   90000   29      F
3  David  Sales   60000   27      M
4   Sara     HR   55000   35      F

In [31]:
# 63

# Replace multiple values.

df = df.replace(["John",90000],["JOHN",100000])

df

    Name   Dept  Salary  Age Gender
0   JOHN    NaN   70000   25      M
1    Sam     HR   50000   31      M
2   Lisa    NaN  100000   29      F
3  David  Sales   60000   27      M
4   Sara     HR   55000   35      F

In [35]:
# 64

# Replace entire department.

df['Dept'].replace({
    np.nan:"Information Technology",
    "HR":"Human Resource",
    "Sales" : "Sales Management"
}, inplace=True)

df

    Name                    Dept  Salary  Age Gender
0   JOHN  Information Technology   70000   25      M
1    Sam          Human Resource   50000   31      M
2   Lisa  Information Technology  100000   29      F
3  David        Sales Management   60000   27      M
4   Sara          Human Resource   55000   35      F

In [36]:
# 65

# Regex replace.

df['Name'] = df['Name'].replace("$","1", regex=True)

df

     Name                    Dept  Salary  Age Gender
0   JOHN1  Information Technology   70000   25      M
1    Sam1          Human Resource   50000   31      M
2   Lisa1  Information Technology  100000   29      F
3  David1        Sales Management   60000   27      M
4   Sara1          Human Resource   55000   35      F