Level 5 - Apply()

In [30]:
import pandas as pd

In [31]:
# create a dataframe of below data

# Name      Dept      Salary    Age
# John      IT        70000      25
# Sam       HR        50000      31
# Lisa      IT        90000      29
# David     Sales     60000      27
# Sara      HR        55000      35
# 


data = {
        'Name': ['John', 'Sam', 'Lisa', 'David', 'Sara'],
        'Dept': ['IT', 'HR', 'IT', 'Sales', 'HR'],
        'Salary': [70000, 50000, 90000, 60000, 55000],
        'Age': [25, 31, 29, 27, 35]
    }
df = pd.DataFrame(data)

In [32]:
# 46

# Increase salary by 10%.
df['Salary'].apply(lambda x: x+(x*0.1))

0    77000.0
1    55000.0
2    99000.0
3    66000.0
4    60500.0
Name: Salary, dtype: float64

In [33]:
df

    Name   Dept  Salary  Age
0   John     IT   70000   25
1    Sam     HR   50000   31
2   Lisa     IT   90000   29
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [34]:
# 47

# Convert to monthly salary.

df['Monthly_Salary']=df['Salary'].apply(lambda x: x//12)

In [35]:
df

    Name   Dept  Salary  Age  Monthly_Salary
0   John     IT   70000   25            5833
1    Sam     HR   50000   31            4166
2   Lisa     IT   90000   29            7500
3  David  Sales   60000   27            5000
4   Sara     HR   55000   35            4583

In [36]:
# 48

# Return

# High

# Medium

# Low

# based on salary.

df['Category'] = df['Salary'].apply(lambda x: "High" if x>=80000 else ("Low" if x<=50000 else "Medium") )

In [37]:
df

    Name   Dept  Salary  Age  Monthly_Salary Category
0   John     IT   70000   25            5833   Medium
1    Sam     HR   50000   31            4166      Low
2   Lisa     IT   90000   29            7500     High
3  David  Sales   60000   27            5000   Medium
4   Sara     HR   55000   35            4583   Medium

In [38]:
# Problem 49 - Extract First Letter

df['Name'].apply(lambda x: x[0])

0    J
1    S
2    L
3    D
4    S
Name: Name, dtype: object

In [39]:
# Problem 50 - Convert Names to Uppercase

df['Name']=df['Name'].apply(lambda x:x.upper())

In [40]:
df

    Name   Dept  Salary  Age  Monthly_Salary Category
0   JOHN     IT   70000   25            5833   Medium
1    SAM     HR   50000   31            4166      Low
2   LISA     IT   90000   29            7500     High
3  DAVID  Sales   60000   27            5000   Medium
4   SARA     HR   55000   35            4583   Medium

In [41]:
# Problem 53 - Convert Gender

df['Gender'] = ["Male", "Male", "Female", "Male", "Female"]

df

    Name   Dept  Salary  Age  Monthly_Salary Category  Gender
0   JOHN     IT   70000   25            5833   Medium    Male
1    SAM     HR   50000   31            4166      Low    Male
2   LISA     IT   90000   29            7500     High  Female
3  DAVID  Sales   60000   27            5000   Medium    Male
4   SARA     HR   55000   35            4583   Medium  Female

In [42]:
df['Gender'] = df['Gender'].apply(lambda x:"M" if x=="Male" else "F")

In [43]:
df

    Name   Dept  Salary  Age  Monthly_Salary Category Gender
0   JOHN     IT   70000   25            5833   Medium      M
1    SAM     HR   50000   31            4166      Low      M
2   LISA     IT   90000   29            7500     High      F
3  DAVID  Sales   60000   27            5000   Medium      M
4   SARA     HR   55000   35            4583   Medium      F

In [44]:
# Problem 51 - Calculate Tax

df['Tax'] = df['Salary'].apply(lambda x: x*0.1 if x<70000 else x*0.2)

df

    Name   Dept  Salary  Age  Monthly_Salary Category Gender      Tax
0   JOHN     IT   70000   25            5833   Medium      M  14000.0
1    SAM     HR   50000   31            4166      Low      M   5000.0
2   LISA     IT   90000   29            7500     High      F  18000.0
3  DAVID  Sales   60000   27            5000   Medium      M   6000.0
4   SARA     HR   55000   35            4583   Medium      F   5500.0

In [47]:
# Problem 52 - Age Category

df['Age_Category'] = df["Age"].apply(lambda x: "Young" if x<30 else ("Senior" if x>50 else "Adult"))

df

,Name,Dept,Salary,Age,Monthly_Salary,Category,Gender,Tax,Age_Category
0,JOHN,IT,70000,25,5833,Medium,M,14000.0,Young
1,SAM,HR,50000,31,4166,Low,M,5000.0,Adult
2,LISA,IT,90000,29,7500,High,F,18000.0,Young
3,DAVID,Sales,60000,27,5000,Medium,M,6000.0,Young
4,SARA,HR,55000,35,4583,Medium,F,5500.0,Adult

In [49]:
# Problem 54 - Calculate Bonus

df['Bonus'] = df['Salary'].apply(lambda x: x*0.2 if x>80000 else (x*0.10 if x<60000 else x*0.15))

df

,Name,Dept,Salary,Age,Monthly_Salary,Category,Gender,Tax,Age_Category,Bonus
0,JOHN,IT,70000,25,5833,Medium,M,14000.0,Young,10500.0
1,SAM,HR,50000,31,4166,Low,M,5000.0,Adult,5000.0
2,LISA,IT,90000,29,7500,High,F,18000.0,Young,18000.0
3,DAVID,Sales,60000,27,5000,Medium,M,6000.0,Young,9000.0
4,SARA,HR,55000,35,4583,Medium,F,5500.0,Adult,5500.0

In [53]:
# Problem 55 - Multiple Column Calculation

df['Total_income'] = df.apply(lambda x: x['Salary'] + x['Bonus'], axis=1)

df

,Name,Dept,Salary,Age,Monthly_Salary,Category,Gender,Tax,Age_Category,Bonus,Total_income
0,JOHN,IT,70000,25,5833,Medium,M,14000.0,Young,10500.0,80500.0
1,SAM,HR,50000,31,4166,Low,M,5000.0,Adult,5000.0,55000.0
2,LISA,IT,90000,29,7500,High,F,18000.0,Young,18000.0,108000.0
3,DAVID,Sales,60000,27,5000,Medium,M,6000.0,Young,9000.0,69000.0
4,SARA,HR,55000,35,4583,Medium,F,5500.0,Adult,5500.0,60500.0