In [ ]:
import pandas as pd
import numpy as np

In [5]:
# create a dataframe of below data

# Name      Dept      Salary    Age
# John      IT        70000      25
# Sam       HR        50000      31
# Lisa      IT        90000      29
# David     Sales     60000      27
# Sara      HR        55000      35



data = {
        'Name': ['John', 'Sam', 'Lisa', 'David', 'Sara'],
        'Dept': ['IT', 'HR', 'IT', 'Sales', 'HR'],
        'Salary': [70000, 50000, 90000, 60000, 55000],
        'Age': [25, 31, 29, 27, 35]
    }
df = pd.DataFrame(data)

In [6]:
df

    Name   Dept  Salary  Age
0   John     IT   70000   25
1    Sam     HR   50000   31
2   Lisa     IT   90000   29
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [7]:
# Beginner
# 11

# Find employees whose salary > 60000.


df[df['Salary']>60000]

   Name Dept  Salary  Age
0  John   IT   70000   25
2  Lisa   IT   90000   29

In [8]:
# 12

# Age < 30.

df[df['Age']<30]

    Name   Dept  Salary  Age
0   John     IT   70000   25
2   Lisa     IT   90000   29
3  David  Sales   60000   27

In [9]:
# 13

# Department == IT

df[df['Dept']=="IT"]

   Name Dept  Salary  Age
0  John   IT   70000   25
2  Lisa   IT   90000   29

In [10]:
# 14

# Department != HR

df[df['Dept']!="HR"]

    Name   Dept  Salary  Age
0   John     IT   70000   25
2   Lisa     IT   90000   29
3  David  Sales   60000   27

In [11]:
# 15

# Salary between 50000 and 80000


df[(df['Salary']>50000) & (df['Salary']<80000)]

    Name   Dept  Salary  Age
0   John     IT   70000   25
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [12]:
# Intermediate
# 16

# IT employees earning >70000


df[(df['Dept']=="IT") & (df['Salary']>70000)]

   Name Dept  Salary  Age
2  Lisa   IT   90000   29

In [13]:
# 17

# HR employees older than 30


df[(df['Dept']=="HR") & (df['Age']>30)]

   Name Dept  Salary  Age
1   Sam   HR   50000   31
4  Sara   HR   55000   35

In [14]:
# 18

# Salary >60000 OR age <30

df[(df['Salary']>60000) | (df['Age']<30)]

    Name   Dept  Salary  Age
0   John     IT   70000   25
2   Lisa     IT   90000   29
3  David  Sales   60000   27

In [15]:
# 19

# Salary >60000 AND age<30

df[(df['Salary']>60000) & (df['Age']<30)]

   Name Dept  Salary  Age
0  John   IT   70000   25
2  Lisa   IT   90000   29

In [16]:
# 20

# Employees NOT in Sales.

df[df['Dept']!="Sales"]

   Name Dept  Salary  Age
0  John   IT   70000   25
1   Sam   HR   50000   31
2  Lisa   IT   90000   29
4  Sara   HR   55000   35

In [17]:
# 21

# Age is one of

# 25
# 29
# 35


df[df['Age'].isin([25,29,35])]

   Name Dept  Salary  Age
0  John   IT   70000   25
2  Lisa   IT   90000   29
4  Sara   HR   55000   35

In [21]:
# 22

# Department starts with "S"

df[df['Dept'].str.startswith("S")]

    Name   Dept  Salary  Age
3  David  Sales   60000   27

In [23]:
# 23

# Name ends with "a"


df[df['Name'].str.endswith("a")]

   Name Dept  Salary  Age
2  Lisa   IT   90000   29
4  Sara   HR   55000   35

In [24]:
# 24

# Names containing "a"

df[df['Name'].str.contains('a')]

    Name   Dept  Salary  Age
1    Sam     HR   50000   31
2   Lisa     IT   90000   29
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [25]:
# 25

# Filter multiple departments

# IT
# HR

df[(df['Dept']=="IT")|(df['Dept']=="HR")]

   Name Dept  Salary  Age
0  John   IT   70000   25
1   Sam   HR   50000   31
2  Lisa   IT   90000   29
4  Sara   HR   55000   35

In [26]:
df

    Name   Dept  Salary  Age
0   John     IT   70000   25
1    Sam     HR   50000   31
2   Lisa     IT   90000   29
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [31]:
# Advanced
# 26

# Top 3 highest salary employees.

df.sort_values(by='Salary', ascending=False).head(3)

    Name   Dept  Salary  Age
2   Lisa     IT   90000   29
0   John     IT   70000   25
3  David  Sales   60000   27

In [34]:
# 27

# Second highest salary.

second = df['Salary'].drop_duplicates().sort_values(ascending=False).iloc[1]

df[df['Salary']==second]

   Name Dept  Salary  Age
0  John   IT   70000   25

In [39]:
# 28

# Youngest employee.

df[df['Age'] == df['Age'].sort_values().iloc[0]]

   Name Dept  Salary  Age
0  John   IT   70000   25

In [40]:
# 29

# Oldest employee.

df[df['Age'] == df['Age'].sort_values().iloc[-1]]

   Name Dept  Salary  Age
4  Sara   HR   55000   35

In [42]:
# 30

# Employees having duplicate salary.

df[df['Salary'].duplicated(keep=False)]

Empty DataFrame
Columns: [Name, Dept, Salary, Age]
Index: []