Level 4 - Sorting

In [9]:
# create a dataframe of below data

# Name      Dept      Salary    Age
# John      IT        70000      25
# Sam       HR        50000      31
# Lisa      IT        90000      29
# David     Sales     60000      27
# Sara      HR        55000      35

import pandas as pd

data = {
        'Name': ['John', 'Sam', 'Lisa', 'David', 'Sara'],
        'Dept': ['IT', 'HR', 'IT', 'Sales', 'HR'],
        'Salary': [70000, 50000, 90000, 60000, 55000],
        'Age': [25, 31, 29, 27, 35]
    }
data = pd.DataFrame(data)

df=data

In [10]:

# 41

# Sort salary ascending.

df.sort_values(by='Salary')

    Name   Dept  Salary  Age
1    Sam     HR   50000   31
4   Sara     HR   55000   35
3  David  Sales   60000   27
0   John     IT   70000   25
2   Lisa     IT   90000   29

In [5]:
# 42

# Sort descending.


df.sort_values(by='Salary',ascending=False)

    Name   Dept  Salary  Age
2   Lisa     IT   90000   29
0   John     IT   70000   25
3  David  Sales   60000   27
4   Sara     HR   55000   35
1    Sam     HR   50000   31

In [ ]:
# 43

# Sort by department then salary.


df.sort_values(by=['Dept', 'Salary'])

    Name   Dept  Salary  Age
1    Sam     HR   50000   31
4   Sara     HR   55000   35
3  David  Sales   60000   27
0   John     IT   70000   25
2   Lisa     IT   90000   29

In [ ]:
# 44

# Sort age descending salary ascending.
df.sort_values(
    by=['Age', 'Salary'],
    ascending=[False, True]
)

    Name   Dept  Salary  Age
1    Sam     HR   50000   31
4   Sara     HR   55000   35
3  David  Sales   60000   27
0   John     IT   70000   25
2   Lisa     IT   90000   29

In [12]:
# 45

# Top 5 salaries.

df.sort_values(by='Salary', ascending=False).iloc[:5]

    Name   Dept  Salary  Age
2   Lisa     IT   90000   29
0   John     IT   70000   25
3  David  Sales   60000   27
4   Sara     HR   55000   35
1    Sam     HR   50000   31