Level 3 - Slicing (.loc/.iloc)

In [1]:
# create a dataframe of below data

# Name      Dept      Salary    Age
# John      IT        70000      25
# Sam       HR        50000      31
# Lisa      IT        90000      29
# David     Sales     60000      27
# Sara      HR        55000      35

import pandas as pd


data = {
        'Name': ['John', 'Sam', 'Lisa', 'David', 'Sara'],
        'Dept': ['IT', 'HR', 'IT', 'Sales', 'HR'],
        'Salary': [70000, 50000, 90000, 60000, 55000],
        'Age': [25, 31, 29, 27, 35]
    }
df = pd.DataFrame(data)

In [5]:
df

    Name   Dept  Salary  Age
0   John     IT   70000   25
1    Sam     HR   50000   31
2   Lisa     IT   90000   29
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [3]:
# 31

# First three rows.

df[:3]

   Name Dept  Salary  Age
0  John   IT   70000   25
1   Sam   HR   50000   31
2  Lisa   IT   90000   29

In [9]:
# 32

# Last two rows.

df[-2:]

    Name   Dept  Salary  Age
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [ ]:
# 33

# Only Name and Salary.

df.iloc[::, ::2]

df[['Name', 'Salary']]

    Name  Salary
0   John   70000
1    Sam   50000
2   Lisa   90000
3  David   60000
4   Sara   55000

In [13]:
# 34

# Rows 3-6.

df[3:6]

    Name   Dept  Salary  Age
3  David  Sales   60000   27
4   Sara     HR   55000   35

In [ ]:
# 35

# Rows where Age >30 and select Salary only.

df[df['Age']>30].loc[::, 'Salary']
df.loc[df['Age'] > 30, 'Salary']

1    50000
4    55000
Name: Salary, dtype: int64

In [18]:
# 36

# Every alternate row.

df.iloc[::2]

   Name Dept  Salary  Age
0  John   IT   70000   25
2  Lisa   IT   90000   29
4  Sara   HR   55000   35

In [19]:
# 37

# Reverse dataframe.

df[::-1]

    Name   Dept  Salary  Age
4   Sara     HR   55000   35
3  David  Sales   60000   27
2   Lisa     IT   90000   29
1    Sam     HR   50000   31
0   John     IT   70000   25

In [21]:
# 38

# Last column only.

df.iloc[::, -1]

0    25
1    31
2    29
3    27
4    35
Name: Age, dtype: int64

In [33]:
# 39

# First row all columns except last.

df.iloc[0:1, :-1]

   Name Dept  Salary
0  John   IT   70000

In [31]:
# 40

# Select

# rows 2 to 8

# columns 1 to 3


df.iloc[2:9,1:4]

    Dept  Salary  Age
2     IT   90000   29
3  Sales   60000   27
4     HR   55000   35