In [1]:
import pandas as pd

In [2]:
# Problem 1

# Create the following DataFrame.

S = {"Name":['John','Sam','Lisa'],
     "Age": [23,25,21],
     "Salary":[45000, 52000, 48000]}

df = pd.DataFrame(S)

df

   Name  Age  Salary
0  John   23   45000
1   Sam   25   52000
2  Lisa   21   48000

In [3]:
# Problem 2

# Print

# first 2 rows
# last row
# column names
# datatype
# shape

print(df.head(2))
print(df.tail(1))
print(df.columns)
print(df.dtypes)
print(df.shape)

   Name  Age  Salary
0  John   23   45000
1   Sam   25   52000
   Name  Age  Salary
2  Lisa   21   48000
Index(['Name', 'Age', 'Salary'], dtype='object')
Name      object
Age        int64
Salary     int64
dtype: object
(3, 3)

In [4]:
# Problem 3

# Change

# Salary

# to

# MonthlySalary

df.rename({'Salary':'MonthlySalary'}, axis=1, inplace=True)

df

   Name  Age  MonthlySalary
0  John   23          45000
1   Sam   25          52000
2  Lisa   21          48000

In [5]:
# Problem 4

# Add new column

# Experience

df['Experience'] = [3,5,4]

df

   Name  Age  MonthlySalary  Experience
0  John   23          45000           3
1   Sam   25          52000           5
2  Lisa   21          48000           4

In [6]:
# Problem 5

# Delete

# Experience


df.drop(columns=['Experience'], axis =1, inplace=True)

df

   Name  Age  MonthlySalary
0  John   23          45000
1   Sam   25          52000
2  Lisa   21          48000

In [7]:
# Problem 6

# Set

# Name

# as index.


df.set_index('Name', inplace=True)
df

      Age  MonthlySalary
Name
John   23          45000
Sam    25          52000
Lisa   21          48000

In [8]:
# Problem 7

# Reset the index.

df.reset_index(inplace=True)
df

   Name  Age  MonthlySalary
0  John   23          45000
1   Sam   25          52000
2  Lisa   21          48000

In [12]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Collecting et-xmlfile
  Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# Problem 8

# Read CSV.

# employees.csv


df = pd.read_excel(r"C:\Users\Acer\Downloads\Practice Datasets-20241123T173327Z-001\Practice Datasets\employee.xlsx")


df.head()

   emp_id first_name last_name  hire_date
0     100     Steven      King 2003-06-17
1     101      Neena   Kochhar 2005-09-21
2     102        Lex   De Haan 2001-01-13
3     103  Alexander    Hunold 2006-01-03
4     104      Bruce     Ernst 2007-05-21

In [ ]:
# Problem 9

# Save dataframe into csv.

pd.DataFrame.to_csv(df, r"employee.csv", index=False)

df.to_csv("employee.csv", index=False)

In [16]:
# Problem 10

# Display dataframe information.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      20 non-null     int64
 1   first_name  20 non-null     object
 2   last_name   20 non-null     object
 3   hire_date   20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 768.0+ bytes